### ISSUE TITLE
Different speeds

### ISSUE THREAD

**Issue by kfrn** [kfrn/film-figures#3]
e.g. 25fps, 16fps (9.5mm?, 8mm), 18fps (8mm, Super 8), etc. 

5da109598ecfb0057ed51c86326f9660b755690d and eb74bafbebe48533f19d625345afdd088ba7e49b set things up for this.

**Comment by kieranjol** [comment]
Is the goal here to have a dropdown with some frequently used speeds, or to allow the user to set the framerate?

**Comment by kfrn** [comment]
Good question! I [_TODO_'d it](https://github.com/kfrn/film-figures/blob/master/src/View.elm#L195) as a selectable option (i.e. HTML `<select>` dropdown), and set up the [type](https://github.com/kfrn/film-figures/blob/master/src/Types.elm#L57) to support that, but I could also go the number `<input>` route. The former is perhaps neater, but latter would give a lot more flexibility, like if your reel is silent and runs at an arbitrary framrate.     
What do you think is preferable?

**Comment by kieranjol** [comment]
I agree that the former would be neater, but perhaps more flexibility is the way to go?

**Comment by kfrn** [comment]
Yeah, it would be advantageous. Though for people who don't know much about film, having a finite list to guide them might be a good thing. Hmmm.

If going with the `<select>` option, which speeds would be good to include? 24, 25, 29.97 (30/1.001), 16, 18 - others?

**Comment by kieranjol** [comment]
I'd have to check our database to see if we ever had anything less than
16..I think you've covered the main ones really...and I get what you mean
about the finite list..I say go with the list!

**Comment by kfrn** [comment]
Different speeds added in 3056294 

TODO: write tests for the different speeds!
